spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true


server:
  port: 3666
